kMotionSensorAccelerometerFileNameChar = 'MotionSensorAccelerometer.csv';
kMotionSensorAccelerometerFileNameString = string(kMotionSensorAccelerometerFileNameChar);
kMotionSensorAccelerometerUncalibratedFileNameChar = 'MotionSensorAccelerometerUncalibrated.csv';
kMotionSensorAccelerometerUncalibratedFileNameString = string(kMotionSensorAccelerometerUncalibratedFileNameChar);
kMotionSensorGyroscopeFileNameChar = 'MotionSensorGyroscope.csv';
kMotionSensorGyroscopeFileNameString = string(kMotionSensorGyroscopeFileNameChar);
kMotionSensorGyroscopeUncalibratedFileNameChar = 'MotionSensorGyroscopeUncalibrated.csv';
kMotionSensorGyroscopeUncalibratedFileNameString = string(kMotionSensorGyroscopeUncalibratedFileNameChar);
kPositionSensorMagneticFieldFileNameChar = 'PositionSensorMagneticField.csv';
kPositionSensorMagneticFieldFileNameString = string(kPositionSensorMagneticFieldFileNameChar);
kPositionSensorMagneticFieldUncalibratedFileNameChar = 'PositionSensorMagneticFieldUncalibrated.csv';
kPositionSensorMagneticFieldUncalibratedFileNameString = string(kPositionSensorMagneticFieldUncalibratedFileNameChar);
kPositionSensorGameRotationVectorFileNameChar = 'PositionSensorGameRotationVector.csv';
kPositionSensorGameRotationVectorFileNameString = string(kPositionSensorGameRotationVectorFileNameChar);
kGnssLocationFileNameChar = 'GnssLocation.csv';
kGnssLocationFileNameString = string(kGnssLocationFileNameChar);
kGnssMeasurementFileNameChar = 'GnssMeasurement.csv';
kGnssMeasurementFileNameString = string(kGnssMeasurementFileNameChar);
kValidateSensorFileList = horzcat(kMotionSensorAccelerometerFileNameString,...
    kMotionSensorAccelerometerUncalibratedFileNameString,...
    kMotionSensorGyroscopeFileNameString,...
    kMotionSensorGyroscopeUncalibratedFileNameString,...
    kPositionSensorMagneticFieldFileNameString,...
    kPositionSensorMagneticFieldUncalibratedFileNameString,...
    kPositionSensorGameRotationVectorFileNameString,...
    kGnssLocationFileNameString,...
    kGnssMeasurementFileNameString);
kValidateSensorFileListLength = length(kValidateSensorFileList);

save('SmartPhoneDataConfig',...
'kMotionSensorAccelerometerFileNameString',...
'kMotionSensorAccelerometerUncalibratedFileNameString',...
'kMotionSensorGyroscopeFileNameString',...
'kMotionSensorGyroscopeUncalibratedFileNameString',...
'kPositionSensorMagneticFieldFileNameString',...
'kPositionSensorMagneticFieldUncalibratedFileNameString',...
'kPositionSensorGameRotationVectorFileNameString',...
'kGnssLocationFileNameString',...
'kGnssMeasurementFileNameString',...
'kValidateSensorFileList',...
'kValidateSensorFileListLength'...
);